### ISSUE TITLE
Useless Lines in Example

### ISSUE THREAD

**Issue by FireNameFN** [discordjs/voice#125]
https://github.com/discordjs/voice/blob/bddd03525a8414d902b67da9e201d23ac8da65b9/examples/music-bot/src/music/subscription.ts#L55-L57

This lines are useless because:

https://github.com/discordjs/voice/blob/bddd03525a8414d902b67da9e201d23ac8da65b9/src/VoiceConnection.ts#L495-L497

**Comment by amishshah** [comment]
Thanks for pointing this out!

Feel free to make a PR to resolve this, otherwise I'll be able to fix it later today.

**Comment by FireNameFN** [comment]
1 hour I tried to make a pull request. Do it yourself.
