### ISSUE TITLE
Self Mute has some issues

### ISSUE THREAD

**Issue by killer069** [discordjs/voice#135]
**Please describe the problem you are having in as much detail as possible:**
While the bot is selfMute, we can still here the song

**Include a reproducible code sample here, if possible:**

```js
const connection = joinVoiceChannel({
        channelId: channel.id,
        guildId: channel.guild.id,
        selfDeaf: false,
        selfMute: true,
        adapterCreator: channel.guild.voiceAdapterCreator,
    });
```

**Further details:**
Self Mute is on but people on server can listen to song. Either this is a feature or a bug.

- @discordjs/voice version:
- Node.js version: v14.17.0
- Operating system: Windows
- Priority this issue should have – as per developers choice. 
- 
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kyranet** [comment]
This is working as expected - selfMute and selfDeaf are client-side only, they're not enforced by Discord's server, in fact, your bot receives voice packets even if selfDeaf is true.

**Comment by killer069** [comment]
Sorry, I clicked wrong button.
