### ISSUE TITLE
JSDoc comments don't reflect current function signatures

### ISSUE THREAD

**Issue by pizzafox** [discordjs/voice#14]
https://github.com/discordjs/voice/blob/a124f95f2eff187f6aba0cc2c506fac84c1444bd/src/DataStore.ts#L35-L37
The parameters in the comment differ from the function definition.

Consider adding [`eslint-plugin-tsdoc`](https://github.com/microsoft/tsdoc/tree/master/eslint-plugin#eslint-plugin-tsdoc) to a linting workflow to automate discovery of such mistakes.

**Comment by amishshah** [comment]
Thanks for the spot! I'll have a look at this now.

**Comment by amishshah** [comment]
Resolved in latest commit.

**Comment by pizzafox** [comment]
Thanks! If you're not already aware, you can amend a commit message to include "Closes #xxx" and GitHub will automatically mark the issue closed.
