### ISSUE TITLE
Node.JS compatibility

### ISSUE THREAD

**Issue by RisedSky** [discordjs/voice#145]
Hello, can you provide a documentation to use this repo in order to import in the Node.JS ? Thanks :)

**Comment by iCrawl** [comment]
The TS examples do not differ vastly from normal JavaScript usage, especially since import/export is also theoretically possible in node.js

All that's needed is to remove the types, which the end-user also can easily do themselves.

**Comment by amishshah** [comment]
In addition, we also have a pure JavaScript example - the radio bot example!
