### ISSUE TITLE
Audioplayer.unpause does not work in node 14.17.1

### ISSUE THREAD

**Issue by cjh980402** [discordjs/voice#146]
```js
queue.audioPlayer.pause(); // queue.audioPlayer is instance of AudioPlayer
// wait some seconds...
queue.audioPlayer.unpause();
```

**Further details:**

- @discordjs/voice version: 0.5.1
- Node.js version: 14.17.1
- Operating system: ubuntu 20.04
- Priority this issue should have – please be realistic and elaborate if possible: The pause works properly, but then the unpause does not. However, when I downgraded nodejs to 14.16.1 unpause works properly.

**Comment by amishshah** [comment]
Can you collect some debug information?

On state transitions, can you collect the old and new status codes of the audio player?

```ts
player.on('stateChange', console.log);
```

**Comment by cjh980402** [comment]
Thank you for your reply, but I don't know why, but yesterday it didn't work, but it's working well after I restarted the server today and tested it again. I'll close the issue.
