### ISSUE TITLE
Audio resources immediately ending

### ISSUE THREAD

**Issue by ThisDudeBoy** [discordjs/voice#150]
**Please describe the problem you are having in as much detail as possible:** Hello, today I have a problem with discord voice.
I tested it on my computer all worked (music bot example). When I install it on my VPS (GalaxyGate) Ubuntu 20.04 it's not working.

No code errors.
Somes cool debug info : 
![image](https://user-images.githubusercontent.com/56303464/124029184-2a033400-d9f5-11eb-8596-18405f7258f6.png)

**Further details:**

- Node.js version: v14.17.1
- Priority this issue should have – please be realistic and elaborate if possible: Yes it's a big bug.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by amishshah** [comment]
After discussion with the issue author, the issue appears to be that audio resources are immediately ending when played on their VPS.

**Comment by amishshah** [comment]
Looked into this with the issue author and came to a fix:

For the basic example, it seemed that the file we were trying to play was being downloaded really slowly and so the stream ended when there weren't enough packets to play.

For the music bot example, it seems that the `youtube-dl` install that comes with `youtube-dl-exec` was complaining about not finding the `python` command. Removed `youtube-dl-exec`. The author of the issue had `youtube-dl` installed on their VPS, so just switched to using that with `ChildProcess.spawn`.
