### ISSUE TITLE
Adapter destroying voiceConnection when client reconnects

### ISSUE THREAD

**Issue by MatteZ02** [discordjs/voice#153]
**Please describe the problem you are having in as much detail as possible:**
VoiceConnection changes state to `destroyed` from `ready` in the middle of playback. Sometimes this occurs after 10 minutes of listening, Sometimes after hours. Yet to find a proper way of reproducing this issue.
![image](https://user-images.githubusercontent.com/51192395/125927664-5a6cd8a9-63e1-4629-8ffe-6df84a45ce66.png)

**Include a reproducible code sample here, if possible:**

```ts
    public async join(
        channel: Discord.VoiceChannel | Discord.StageChannel
    ): Promise<VoiceConnection | null> {
        try {
            this.voiceChannel = channel;
            const connection: VoiceConnection =
                getVoiceConnection(this.guild.id) ??
                joinVoiceChannel({
                    channelId: channel.id,
                    guildId: this.guild.id,
                    //@ts-ignore
                    adapterCreator: createDiscordJSAdapter(channel),
                    debug: this.client.config.debug.voiceConnection
                });
            this.connection = connection;
            this.connection
                .once("error", err => {
                    this.connection = null;
                    this.emit("error", err);
                })
                .on("stateChange", async (oldState, newState) => 
                    console.log(`oldStatus: ${oldState.status}, newStatus: ${newState.status}`)
                )
                .on("debug", console.log);
            return (
                (await entersState(connection, VoiceConnectionStatus.Ready, 15e3).catch(e => {
                    console.error(e);
                    if (connection.state.status !== "destroyed") connection.destroy();
                    if (this.exists) this._timeout();
                })) || null
            );
        } catch (error) {
            this.client.player.delete(channel.guild?.id as string);
            console.log("failed to obtain a voiceConnection");
            console.error(error);
            this.textChannel?.send(this.client.messages.error + error.toString());
            return null;
        }
    }
```

**Further details:**

- @discordjs/voice version: 0.5.4
- Node.js version: 14.15.0
- Operating system: Ubuntu 20.04 (also occurs on windows 10 with older versions of djs/voice)
- Priority this issue should have – please be realistic and elaborate if possible: medium to high. It really does mess with playback when occurring in the middle of playing.

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_VOICE_STATES, GUILD_MESSAGES
- other: none

**Comment by SpaceEEC** [comment]
Can you try getting a stacktrace in the `statusUpdate` event?
Something like `new Error().stack` should do the trick.

**Comment by MatteZ02** [comment]
Ill do. Might take up to a few days for me to catch the error again.

**Comment by MatteZ02** [comment]
![image](https://user-images.githubusercontent.com/51192395/126011109-05d0d48a-8aca-4f4c-953f-f63250fa8091.png)
Alright got the stack trace after 2 hours of continuous listening (on the same connection)

**Comment by amishshah** [comment]
Can you share your Player.js file?

**Comment by MatteZ02** [comment]
the uncompiled ts file of the player is 930 lines. I can send the entire thing if needed but is there any part you'd like to see in particular?

**Comment by MatteZ02** [comment]
> ![image](https://user-images.githubusercontent.com/51192395/126011109-05d0d48a-8aca-4f4c-953f-f63250fa8091.png)
> Alright got the stack trace after 2 hours of continuous listening (on the same connection)

Unfortunately i didn't take a proper look at the chain of errors that occurred around this stack.
Anyhow i just ran into a different one. Seems like the ws shard closed which resulted in the voiceConnection being destroyed by the adapter.
![image](https://user-images.githubusercontent.com/51192395/126047611-1653808f-b905-4ba6-be0b-e98919f92d19.png)

**Comment by MatteZ02** [comment]
after 5 hours of debugging last night i got the error again. This time with debugging enabled for my djs client.
![image](https://user-images.githubusercontent.com/51192395/126061577-b26c9da0-2648-42f5-a66b-10c089c3a379.png)
so what happened was that the ws reconnected which caused the adapter to destroy the voiceConnection.

**Comment by MatteZ02** [comment]
Alright i got it. So the reason the voiceConnection is destroyed is due to the adapter function `cleanupGuilds` which will delete the existing voiceConnections. Just by commenting out `adapters.get(guildID)?.destroy();` the problem went away.

**Comment by amishshah** [comment]
This is odd, the intended behaviour of the adapter provided by discord.js is to only destroy once the main WebSocket shard has disconnected and will not attempt to reconnect.

I will take a look at fixing this adapter.
