### ISSUE TITLE
Changing the playbackDuration of a resource, doesn't seek it

### ISSUE THREAD

**Issue by stijnb1234** [discordjs/voice#168]
**Please describe the problem you are having in as much detail as possible:**
When I use `resource.playbackDuration = seek;`, it doesn't seek the resource when I play it. It will just start playing at the beginning.

**Include a reproducible code sample here, if possible:**

```js
const connection = joinVoiceChannel({
    channelId: channel.id,
    guildId: channel.guild.id,
    adapterCreator: channel.guild.voiceAdapterCreator,
});

const player = createAudioPlayer();

const seek = 5000; //Seek 5 sec

const resource = createAudioResource("./music.mp3", { inlineVolume: true });
resource.volume.setVolume(0.4);
resource.playbackDuration = seek;

player.play(resource);

connection.subscribe(player);
```

**Further details:**

- @discordjs/voice version: 0.5.6
- Node.js version: 16.6.1
- Operating system: Windows 11
- Priority this issue should have – please be realistic and elaborate if possible: Moderate

**Relevant client options:**

- partials: none
- gateway intents: GUILDS, GUILD_BANS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, GUILD_MEMBERS, GUILD_VOICE_STATES
- other: none

**Comment by amishshah** [comment]
playbackDuration is intended as a read-only property, changing it won't do anything.

This library does not yet support seeking, if you'd like to do it, you'd need to use FFmpeg or some other tool.

**Comment by stijnb1234** [comment]
Ah, okay. Because it's not defined as readOnly in the code itself. :P

https://github.com/discordjs/voice/issues/30#issuecomment-774542836

Here you indicate that examples will come for it. Where can I find them? I'm not so familiar with ffmpeg that I can put that together myself. :P

**Comment by stijnb1234** [comment]
#161 did it for me. ;)
