### ISSUE TITLE
AudioResource.volume.volumeDecibels returns NaN

### ISSUE THREAD

**Issue by WOZARDLOZARD** [discordjs/voice#173]
**Please describe the problem you are having in as much detail as possible:**
When trying to access the volume, in decibels, from an audio resource, the result is NaN, even though it's supposed to be a number.

Screenshot:
<img width="643" alt="screenshot" src="https://user-images.githubusercontent.com/53450976/128757344-3e2d12b2-3773-4011-ae3d-8a04da5e108f.png">

**Include a reproducible code sample here, if possible:**

```js
const { createAudioResource, StreamType } = require('@discordjs/voice');

const args = ['-reconnect', '1', '-reconnect_streamed', '1', '-reconnect_on_network_error', '1', '-reconnect_on_http_error', '4xx,5xx', '-reconnect_delay_max', '30', '-analyzeduration', '0', '-loglevel', '0', '-acodec', 'libopus', '-f', 'opus', '-ar', '48000', '-ac', '2'];

const stream = ytdl("youtube_url", { filter: "audioonly", highWaterMark: 1 << 25, requestOptions: { headers: { cookie: process.env.YTCOOKIE } } }).pipe(new FFmpeg({
    args,
})).pipe(new PassThrough({
    highWaterMark: 1,
}));

const resource = createAudioResource(stream, { inputType: StreamType.OggOpus, inlineVolume: true });

console.log(resource.volume.volumeDecibels); // NaN
```

**Further details:**

- @discordjs/voice version: 0.5.6
- Node.js version: 16.6.1
- Operating system: MacOS Big Sur
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: all
- gateway intents: GUILDS, GUILD_MESSAGES, GUILD_MEMBERS, GUILD_VOICE_STATES
- other: 
Dependency report:
```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.5.6
- prism-media: 1.3.1

Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5

FFmpeg
- version: 4.4-tessus  https://evermeet.cx/ffmpeg/ 
- libopus: yes
--------------------------------------------------
```

**Comment by DevAndromeda** [comment]
This is a bug in **prism-media** and was fixed by https://github.com/amishshah/prism-media/pull/82

I guess that version is not yet released

**Comment by WOZARDLOZARD** [comment]
Looks like following the fixes in the prism-media PR indeed fixed the issue, thank you!
