### ISSUE TITLE
Shard reconnect when trying to join voice channel using discordjs/voice

### ISSUE THREAD

**Issue by phamleduy04** [discordjs/voice#179]
**Please describe the problem you are having in as much detail as possible:**
When I'm trying to join a voice channel using `joinVoiceChannel()`, the shard restart itself and the bot won't join a channel.
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
const { joinVoiceChannel } = require('@discordjs/voice');
module.exports = {
    name: 'test',
    run: async (client, message, args) => {
        const voiceChannel = message.member.voice.channel;
        if (!voiceChannel) return message.reply('Join channel pls.');
        await joinVoiceChannel({
            channelId: voiceChannel.id,
            guildID: message.guild.id,
            selfDeaf: true,
            adapterCreator: message.guild.voiceAdapterCreator,
        });
    },
};
```

**Further details:**

- @discordjs/voice version: 0.5.3
- Node.js version: 16.6.2
- Operating system: macOS 11.5.1
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: `['MESSAGE', 'CHANNEL', 'REACTION', 'USER']`
- gateway intents: `GUILDS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, GUILD_VOICE_STATES, GUILD_WEBHOOKS, DIRECT_MESSAGES, GUILD_INVITES`
- other: none

**Comment by muhimur9049** [comment]
@phamleduy04 You need to change this part to `guildId: message.guild.id` and then it will join the voice channel.

As for the shard restarting itself, I'm unable to reproduce it. But by changing `guildID` to `guildId`, it should join.
![image](https://user-images.githubusercontent.com/52611945/129242168-a026a91e-0d46-4357-9f15-11cf4d3a475c.png)

**Comment by phamleduy04** [comment]
oh yes my bad, when I changed to `guildId` it join and I no longer have issue with shard anymore, thanks.
