### ISSUE TITLE
Player and Connection getter's functions are not working.

### ISSUE THREAD

**Issue by bymayfe** [discordjs/voice#180]
**Please describe the problem you are having in as much detail as possible: new AudioPlayer()'s functions and getVoiceConnection()'s functions are not working. But joinVoiceChannel()'s and createAudioPlayer()'s functions are working.**

**Include a reproducible code sample here, if possible:
new AudioPlayer().stop() and getVoiceConnection(message.guild.id).subscribe(player) **

```js
  var player = new AudioPlayer(message.guild.id);
  player.stop();
  player.pause(); 
  player.unpause()
  
  
  /*-------------OTHER FUNCTION----------------*/
  var connection = getVoiceConnection(message.guild.id);
  connection.subscribe(player);
  
  // Dont same function 
  var connection = getVoiceConnection(message.guild.id);
  var connection = joinVoiceChannel()
  
  //and
   var player = new AudioPlayer();
   var player = createAudioPlayer()
```

**Further details:**

- @discordjs/voice version: v0.6.0
- Node.js version: v16.6.2
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible: yes

**Relevant client options:**

- partials: ['MESSAGE', 'CHANNEL', 'REACTION'],
- gateway intents: 32767
- other:    restTimeOffset: 100
![image_2021-08-13_005629](https://user-images.githubusercontent.com/52834828/129275197-9eb633c4-79ce-412a-96c2-a381243a6203.png)
![image_2021-08-13_010438](https://user-images.githubusercontent.com/52834828/129275900-bc7a8332-75d3-4047-9510-1597b741184e.png)
![image_2021-08-13_011217](https://user-images.githubusercontent.com/52834828/129276609-0eceaffb-a2f5-46a6-b08e-21d6b5518a1a.png)

**Comment by killer069** [comment]
First of all, there is no function like  `connection.subscripte(player);` 

Secondly, you don't need to create AudioPlayer in that manner :

Refer to this for creating [AudioPlayer](https://deploy-preview-595--discordjs-guide.netlify.app/voice/audio-player.html#creation)

You don't need to pass a guild id in AudioPlayer like that.

Moreover, voice connection .subscribe is only a function when a connection is in ready state.

The last image is also true as [connection.subscribe()](https://discordjs.github.io/voice/classes/voiceconnection.html#subscribe) returns a PlayerSubscription not a connection.

First Read DOCS completely and then create a issue

**Comment by bymayfe** [comment]
Are there player and connection I created and a function that the connection from somewhere else and use ?

**Comment by killer069** [comment]
> I already read DOCS completely and ı know create player.
> My question are =>
> Are there player and connection I created and a function that the connection from somewhere else and use ?
> `connection.subscribe(player);` function => sorry for the spelling mistake

Probably your codes are somewhere confusing you and forcing you to create this issue.

First start with basic examples as in guide and then start making classes.

**Comment by bymayfe** [comment]
ı know ı make already system but 
The main thing I was wondering was how I could use it with getter functions. When I tried, I couldn't get the system to work with the getter functions.

**Comment by killer069** [comment]
> ı know ı make already system but
> The main thing I was wondering was how I could use it with getter functions. When I tried, I couldn't get the system to work with the getter functions.

Leave everything aside, tell me how can you pause a player which is in idle state ???
As clearly seen in your images

![image](https://user-images.githubusercontent.com/52834828/129275900-bc7a8332-75d3-4047-9510-1597b741184e.png)

**Comment by bymayfe** [comment]
İst just example. Try getter functins stop pause and unpause and reply please.
'''js
getVoiceConnection(message.guild.id) || new AudioPlayer()
'''

**Comment by killer069** [comment]
> Ist just example. Try getter functins stop pause and unpause and reply please.
> 
> ```js
> getVoiceConnection(message.guild.id) || new AudioPlayer()
> ```

Ok taking your same example. First of all, AudioPlayer takes options not guild ID. So leaving that aside, now let's talk about stop and pause and unpause functions.

Suppose You have a music player ( for e.g. Groove Music ) and you open it. It will be in idle state since player has nothing to load.

Once you click a music file, its state changes from idle to playing and also controls come up. Then in playing state only, you can pause, unpause and stop functions will work. as see by your images all those functions are working great you just need to play a resource.

**Comment by bymayfe** [comment]
Okey. Let me try to explain it like this.
-- https://youtu.be/-CdaH4l5Cd8

**Comment by killer069** [comment]
> Okey. Let me try to explain it like this.
> -- https://youtu.be/-CdaH4l5Cd8
> 
> if ı set player and connection new Map(); ı can get and use pause unpause and stop function.
> 
> and maybe getVoicePlayer function must be added

Thanks for the video, I fully understand your problem now.

You can create your own getter function named getVoicePlayer() by this code :

```js
const { getVoiceConnection } = require('@discordjs/voice');

function getVoicePlayer(guild_id){
    let connection = getVoiceConnection(guild_id);
    if(!connection) return undefined
    if(connection.state?.subscription?.player) return connection.state.subscription.player
    else return undefined
}
```

**Comment by bymayfe** [comment]
Thank you so much for the explanation. So how can i make a subscription with getVoiceConnection() function. can i do it is it possible

**Comment by bymayfe** [comment]
Okey ı find this function thanks for interest <3

**Comment by killer069** [comment]
No Problem 👍
