### ISSUE TITLE
[Types] WebSocket types error

### ISSUE THREAD

**Issue by ibaraki-douji** [discordjs/voice#182]
I just install the npm package and in the Types (dist/index.d.ts) and the WebSocket import is invalid.

Initial :
```js
import WebSocket, { MessageEvent } from 'ws';
```

And what it should be :
```js
import { MessageEvent } from 'ws';
import WebSocket = require('ws');
```

Because `ws` package use `export = ` for his lib.

**Comment by vaporox** [comment]
You probably didn't enable `esModuleInterop` in your tsconfig, which allows importing it like that.
