### ISSUE TITLE
Discord.JS v13 voice library crashing

### ISSUE THREAD

**Issue by foxikdev** [discordjs/voice#195]
**Please describe the problem you are having in as much detail as possible:**

My music bot for some reason crashed (it's not like I never had it before, I just made it) and I couldn't figure out why. 
(This is almost the same as https://github.com/discordjs/voice/issues/148, but first time it crashed it was 4 minutes, now it was a lot longer)

**Include a reproducible code sample here, if possible:**

```js
const player = createAudioPlayer();
            const str = ytdl(inl.shortUrl, {
                filter: 'audioonly',
                quality: 'lowest'
            });
            const { stream, type } = await demuxProbe(str);
            const res = require('@discordjs/voice').createAudioResource(stream, { inputType: type } )
            player.play(res);
            getVoiceConnection('859750905838043157').subscribe(player);
            player.once(AudioPlayerStatus.Idle, () => {
                current++;
                nxt();
            });
```

**Further details:**

- @discordjs/voice version: 0.6.0
- Node.js version: v16.7.0
- Operating system: Windows 10, 64-bit x64, 21H1 build 19043.1165
- Priority this issue should have – please be realistic and elaborate if possible: bug, medium

**Relevant client options:**

- partials: none
- gateway intents: all (I used Object.keys(Intents.FLAGS))
- other: none

**Comment by foxikdev** [comment]
Here it is, sorry for the delay it crashed really late: AudioPlayerError: aborted
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketCloseListener (node:_http_client:407:19)
    at TLSSocket.emit (node:events:406:35)
    at node:net:672:12
    at TCP.done (node:_tls_wrap:580:7) {
  resource: AudioResource {
    playbackDuration: 104360,
    started: true,
    silenceRemaining: -1,
    edges: [ [Object] ],
    playStream: WebmDemuxer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _remainder: null,
      _length: 688128,
      _count: 688096,
      _skipUntil: null,
      _track: [Object],
      _incompleteTrack: {},
      _ebmlFound: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    metadata: null,
    silencePaddingFrames: 5,
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      subscribers: [Array],
      _state: [Object],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    }
  }
}

**Comment by killer069** [comment]
> Here it is, sorry for the delay it crashed really late:
> AudioPlayerError: aborted

This is a error from ytdl-core, discord.js voice can't do anything about it

For more info : see [this](https://github.com/fent/node-ytdl-core/issues/902)

**Comment by killer069** [comment]
Anyone close this issue.
