### ISSUE TITLE
trying to establish a connection always fail for timeout while waiting status to be ready

### ISSUE THREAD

**Issue by dahool** [discordjs/voice#203]
I'm trying to establish a connection to a voice channel. I can see the bot actually connects to the channel, but it always get aborted after timeout because the connection never switch to **ready**, it always stay at **signalling**

```js
async function connectToChannel(channel) {
  const connection = joinVoiceChannel({
    channelId: channel.id,
    guildId: channel.guild.id,
    adapterCreator: channel.guild.voiceAdapterCreator,
  });
  try {
    // this always fail with timeout
    await entersState(connection, VoiceConnectionStatus.Ready, 30_000);
    return connection;
  } catch (error) {
    connection.destroy();
    throw error;
  }
}
```

**Further details:**

- @discordjs/voice version: 0.6.0
- Node.js version: 16.6.1
- Operating system: Win/Linux
- Priority this issue should have – please be realistic and elaborate if possible: HIGH

**Comment by killer069** [comment]
You need `GUILD_VOICE_STATES` intent also.

Add that and try again.

**Comment by dahool** [comment]
Adding `GUILD_VOICE_STATES` worked. Could that be added to the documentation please?

**Comment by killer069** [comment]
@dahool 

discord.js docs states very clearly about this. As `discordjs/voice` is a separate package, so it doesn't mentions separately.

![image](https://user-images.githubusercontent.com/65385476/134556774-718519a4-745b-4e60-bac3-b13dd6f448d3.png)

Please close this issue.

**Comment by dahool** [comment]
true, but since is a separate package with its own documentation, it would be nice if it is documented there too.
