### ISSUE TITLE
entersState seems to be locking the thread for itself, causing abortions to always happen

### ISSUE THREAD

**Issue by yellows111** [discordjs/voice#218]
Hey, trying to play around with discord.js v13/voice 0.6.0, and noticed this caveat (very quickly) after reading the examples.

```js
entersState(connection, VoiceConnectionStatus.Ready, 30e3); // As mentioned and used in samples, ala /examples directory on repo.
console.log("Usually somehting would run here, but an abortion would not cause this to run");
```
and for the part of the interactions handler im using:
```js
case 'join': {
	const channel = interaction.member?.voice.channel;
		if (channel) {
			try {
				await interaction.reply('Should of joined voice channel?');
				const connection = await connectToChannel(channel); // connectToChannel function is verbatim from the Basic Example
				// ...
```
**Further details:**

- @discordjs/voice version: 0.6.0
- Node.js version: 16.11.0
- Operating system: Windows 10 x86_64 | 10.0.19041
- Priority this issue should have – Kind of hard to use the library if it doesn't work?

**Relevant client options:**

- partials: none
- gateway intents: none
- other: Intents.FLAGS.GUILDS, using interactions

**Comment by Hashiphoto** [comment]
Not sure if you're experiencing the same issue I was, but I had to include ` Intents.FLAGS.GUILD_VOICE_STATES` to get past the `entersState` line. The client won't know what state the connection is in without that intent.

**Comment by yellows111** [comment]
Oh. my bad, that fixed it, should really of looked into what intents i'll use.
