### ISSUE TITLE
High ram usage

### ISSUE THREAD

**Issue by pauldb09** [discordjs/voice#226]
### Issue description

My bot is using 5gb of ram with discord.js/voice and only 1gb with lavalink.
Just create a bot with lavalink and another with discord.js/voice and you will see.
https://cdn.discordapp.com/attachments/852128888128929802/903544140535578664/unknown.png

### @discordjs/voice version

oldest

### Node.js version

16

### Operating system

Ubuntu 20

### Priority this issue should have

High (immediate attention needed)

**Comment by iCrawl** [comment]
This needs way more information, also duplicate of #164
