### ISSUE TITLE
Create comparison documentation against Discord.js v12

### ISSUE THREAD

**Issue by amishshah** [discordjs/voice#30]
This documentation will serve to:

- Inform users of how they can start to migrate to this module
- The benefits of moving to this module
- Some features that will be missing from this module and explanations as to why
  - Audio seeking
  - Voice receive (:cry:)

**Comment by galnir** [comment]
Audio seeking meaning [seek option](https://discord.js.org/#/docs/main/master/typedef/StreamOptions)?

**Comment by kyranet** [comment]
> Audio seeking meaning [seek option](https://discord.js.org/#/docs/main/master/typedef/StreamOptions)?

Yes.

**Comment by amishshah** [comment]
The reasoning behind this is that `seek` only works for streams that use FFmpeg. It is misleading to allow a seek property that may be ignored for some use cases and it adds a lot of overall bloat to the internals by including this. It also begs the question why we choose to allow seek but not other FFmpeg filters and options.

The most robust solution is making the user take responsibility for this - if you want to specify seek or any other FFmpeg options, you should create your own FFmpeg transcoder.

**Comment by galnir** [comment]
> The reasoning behind this is that `seek` only works for streams that use FFmpeg. It is misleading to allow a seek property that may be ignored for some use cases and it adds a lot of overall bloat to the internals by including this. It also begs the question why we choose to allow seek but not other FFmpeg filters and options.
> 
> The most robust solution is making the user take responsibility for this - if you want to specify seek or any other FFmpeg options, you should create your own FFmpeg transcoder.

Something like [this](https://github.com/fent/node-ytdl-core/blob/master/example/time_range.js)?
I would be grateful if you could give me a basic example

**Comment by amishshah** [comment]
@galnir some examples will be provided in the guide :+1:

**Comment by amishshah** [comment]
This is being tracked in https://github.com/discordjs/guide/pull/595, so I'm closing this.
