### ISSUE TITLE
Auto-hang up the call if there is only one participant for more than 2 minutes

### ISSUE THREAD

**Issue by omarbelkady** [discordjs/voice#81]
It would be nice if discord can automatically end the voice call if there is only participant in the group call(which had 2 or more participants obviously) for more than 2 minutes.

Thank you so much

**Comment by amishshah** [comment]
I think this is too opinionated to include within the library itself. Furthermore, `@discordjs/voice` has no awareness of who is in the voice channel (this is done by the supporting library, e.g. Discord.js). If you'd like this functionality, you would be best off implementing it yourself.

**Comment by advaith1** [comment]
If you are requesting a Discord feature, and you are not coding a bot using `@discordjs/voice`, you can make Discord feature requests at https://dis.gd/feedback and contact Discord Support at https://dis.gd/support

Discord.js is not by Discord.
